use NAVEEN

select * from [dbo].[SQLFILE]



select 
[FOOD RETAILERS] as  RETAILERS
,[BC SUPER CATEGORY] AS BC_SUPER_CATEGORY
,[BRAND HIGH] AS BRAND_HIGH
,[BRAND LOW] AS BRAND_LOW
,[LONG PRODUCT DESCRIPTION] AS LONG_PRODUCT_DESCRIPTION
,[WEEKS] AS WEEKS
,[UNITS] AS UNITS
,[$] AS DOLLAR
,[$ YA] AS DOLLAR_YA
,[Avg Unit Price] AS AVG_UNIT_PRICE
INTO FILE1
FROM [dbo].[SQLFILE]

SELECT * FROM SQL1

SELECT *,RIGHT([LONG_PRODUCT_DESCRIPTION],12) AS ITEM_NUMBER,
 CAST(RIGHT(WEEKS,8) AS DATE) AS WEEK_TEXT,
 LEFT(RIGHT([LONG_PRODUCT_DESCRIPTION],12),9) AS DP_PARENT,
 DATEADD (DAY,-91,CAST(RIGHT(WEEKS,8) AS DATE)) AS PREV_13_WEEKS,
 DATEADD (DAY,-21,CAST(RIGHT(WEEKS,8) AS DATE)) AS BASE_START,
 DATEADD (DAY,21,CAST(RIGHT(WEEKS,8) AS DATE)) AS BASE_END,
 UPPER ([RETAILERS]) AS RETAILER
INTO SQL1
FROM FILE1

SELECT * FROM [dbo].[FILE3]

SELECT *,[WEEK_TEXT] AS XDATE 
INTO SEQUEL
FROM [dbo].[FILE3]

SELECT * FROM SQL3

SELECT UPPER([RETAILERS]) AS RETAILERS
,[BC_SUPER_CATEGORY]
,[BRAND_HIGH],[BRAND_LOW],[LONG_PRODUCT_DESCRIPTION],[WEEKS],[UNITS]
,[DOLLAR],[DOLLAR_YA],[AVG_UNIT_PRICE],[ITEM_NUMBER],[XDATE]
,[DP_PARENT],[WEEK_TEXT],[PREV_13_WEEKS],[BASE_START],[BASE_END] 
INTO SQL3
FROM [dbo].[SEQUEL]

 SELECT *,(select sum(B.[DOLLAR]) from [dbo].[SQL3] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[WEEK_TEXT] >=A.[PREV_13_WEEKS] and B.[WEEK_TEXT]<=A.[WEEK_TEXT] and B.[RETAILERS]=A.[RETAILERS] ) AS L13_DOLLAR
 ,(select sum(B.[DOLLAR_YA]) from [dbo].[SQL3] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[WEEK_TEXT] >=A.[PREV_13_WEEKS] and B.[WEEK_TEXT]<=A.[WEEK_TEXT] and B.[RETAILERS]=A.[RETAILERS] ) AS L13_DOLLAR_YA
  ,(select MIN(B.[UNITS]) from [dbo].[SQL3] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[WEEK_TEXT] >=A.[BASE_START] and B.[WEEK_TEXT]<=A.[BASE_END] and B.[RETAILERS]=A.[RETAILERS] ) AS BASE_SALES_UNITS
 INTO SQL4
  from [dbo].[SQL3] A

select *,(select MIN(B.[WEEK_TEXT]) from [dbo].[SQL4] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[UNITS]=A.[UNITS] and B.[BASE_SALES_UNITS]=A.[BASE_SALES_UNITS]) AS BASE_WEEK
 into SQL5
 from [dbo].[SQL4] A 

  SELECT *,(select MIN(B.[DOLLAR]) from [dbo].[SQL5] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[UNITS]=A.[UNITS] AND B.[BASE_SALES_UNITS]=A.[BASE_SALES_UNITS] and B.[WEEK_TEXT]=A.[WEEK_TEXT] 
 AND B.[BASE_WEEK] =A.[BASE_WEEK]and B.[RETAILERS]=A.[RETAILERS] ) AS BASE_SALES,
 dateadd(day,-1,[WEEK_TEXT]) as X_DATE,
 into SQL6
 from [dbo].[SQL5] A


 SELECT *,
 CASE 
    WHEN[BASE_SALES_UNITS]  <> 0 THEN [BASE_SALES]/[BASE_SALES_UNITS]
    ELSE 0 
  END AS REGULAR_PRICE_PER_UNIT
  INTO SQL8
FROM SQL6;

SELECT * FROM SQL8


select [L13_DOLLAR]
,round([L13_DOLLAR],2) as A,
round([L13_DOLLAR_YA],2) as B,
round([BASE_SALES],2) as C from SQL6

select [RETAILERS]
,[BC_SUPER_CATEGORY]
,[BRAND_HIGH]
,[BRAND_LOW]
,[LONG_PRODUCT_DESCRIPTION]
,[WEEKS]
,[UNITS]
,[DOLLAR]
,[DOLLAR_YA]
,[AVG_UNIT_PRICE]
,[ITEM_NUMBER]
,[XDATE]
,[DP_PARENT]
,[WEEK_TEXT]
,[PREV_13_WEEKS]
,[BASE_START]
,[BASE_END]
,round([L13_DOLLAR],2) AS L13_DOLLAR
,round([L13_DOLLAR_YA],2)L13_DOLLAR_YA
,round([BASE_SALES],2) as BASE_SALES_UNITS
,[BASE_WEEK]
,[BASE_SALES]
,[X_DATE]
,[REGULAR_PRICE_PER_UNIT]
into SQL7
from SQL8

 select *, dateadd(day,91,[WEEK_TEXT]) as NEXT_13_WEEKS ,
 dateadd(WEEK,-1,[WEEK_TEXT]) as BEFORE_WEEKS,
 dateadd(WEEK,1,[WEEK_TEXT]) as AFTER_WEEKS,
 dateadd(WEEK,52,[WEEK_TEXT]) as ONE_YEAR,
 dateadd(MONTH,3,[WEEK_TEXT]) as AFTER_3_MONTH,
 dateadd(MONTH,-5,[WEEK_TEXT]) as BEFORE_5_MONTHS,
 dateadd(MONTH,6,[WEEK_TEXT]) as HALF_YEAR,
 dateadd(QUARTER,2,[WEEK_TEXT]) as SECOND_QUARTER,
 dateadd(QUARTER,3,[WEEK_TEXT]) as THIRD_QUARTER,
 dateadd(YEAR,-4,[WEEK_TEXT]) as PREV_4_YEARS,
 dateadd(YEAR,4,[WEEK_TEXT]) as AFTER_4_YEARS
 INTO SQL9
 FROM [dbo].[SQL8]

 SELECT * FROM SQL9


  SELECT *,ROUND((select MIN(B.[DOLLAR]) from [dbo].[SQL9] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[WEEK_TEXT] >=A.[PREV_13_WEEKS] and B.[WEEK_TEXT]<=A.[WEEK_TEXT]
 and B.[RETAILERS]=A.[RETAILERS]),2 ) AS MIN_L13_DOLLAR,
 ,ROUND((select MIN(B.[DOLLAR_YA]) from [dbo].[SQL9] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[WEEK_TEXT] >=A.[PREV_13_WEEKS] and B.[WEEK_TEXT]<=A.[WEEK_TEXT] 
 and B.[RETAILERS]=A.[RETAILERS]),2 ) AS MIN_L13_DOLLAR_YA
  ,ROUND((select SUM(B.[UNITS]) from [dbo].[SQL9] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[WEEK_TEXT] >=A.[BASE_START] and B.[WEEK_TEXT]<=A.[BASE_END] 
 and B.[RETAILERS]=A.[RETAILERS]),2 ) AS SUM_BASE_SALES_UNITS
  ,ROUND((select MAX(B.[DOLLAR]) from [dbo].[SQL9] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[WEEK_TEXT] >=A.[PREV_13_WEEKS] and B.[WEEK_TEXT]<=A.[WEEK_TEXT]
 and B.[RETAILERS]=A.[RETAILERS]),2 ) AS MAX_L13_DOLLAR
 ,ROUND((select MAX(B.[DOLLAR_YA]) from [dbo].[SQL9] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[WEEK_TEXT] >=A.[PREV_13_WEEKS] and B.[WEEK_TEXT]<=A.[WEEK_TEXT] 
 and B.[RETAILERS]=A.[RETAILERS]),2 ) AS MAX_L13_DOLLAR_YA
  ,ROUND((select MAX(B.[UNITS]) from [dbo].[SQL9] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[WEEK_TEXT] >=A.[BASE_START] and B.[WEEK_TEXT]<=A.[BASE_END] 
 and B.[RETAILERS]=A.[RETAILERS]),2 ) AS MAX_BASE_SALES_UNITS
 ,ROUND((select AVG(B.[DOLLAR]) from [dbo].[SQL9] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[WEEK_TEXT] >=A.[PREV_13_WEEKS] and B.[WEEK_TEXT]<=A.[WEEK_TEXT]
 and B.[RETAILERS]=A.[RETAILERS]),2 ) AS AVG_L13_DOLLAR
 ,ROUND((select AVG(B.[DOLLAR_YA]) from [dbo].[SQL9] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[WEEK_TEXT] >=A.[PREV_13_WEEKS] and B.[WEEK_TEXT]<=A.[WEEK_TEXT] 
 and B.[RETAILERS]=A.[RETAILERS]),2 ) AS AVG_L13_DOLLAR_YA
  ,ROUND((select AVG(B.[UNITS]) from [dbo].[SQL9] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[WEEK_TEXT] >=A.[BASE_START] and B.[WEEK_TEXT]<=A.[BASE_END] 
 and B.[RETAILERS]=A.[RETAILERS] ),2) AS AVG_BASE_SALES_UNITS
 INTO SQL10
  from [dbo].[SQL9] A



  select *,(select Max(B.[WEEK_TEXT]) from [dbo].[SQL10] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[UNITS]=A.[UNITS] and B.[BASE_SALES_UNITS]=A.[BASE_SALES_UNITS]) AS MAX_BASE_WEEK
 INTO SQL11
 FROM SQL10 A

   SELECT *,(select MAX(B.[DOLLAR]) from [dbo].[SQL11] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[UNITS]=A.[UNITS] AND B.[BASE_SALES_UNITS]=A.[BASE_SALES_UNITS] and B.[WEEK_TEXT]=A.[WEEK_TEXT] 
 AND B.[BASE_WEEK] =A.[BASE_WEEK]and B.[RETAILERS]=A.[RETAILERS] ) AS MAX_BASE_SALES,
  (select SUM(B.[DOLLAR]) from [dbo].[SQL11] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[UNITS]=A.[UNITS] AND B.[BASE_SALES_UNITS]=A.[BASE_SALES_UNITS] and B.[WEEK_TEXT]=A.[WEEK_TEXT] 
 AND B.[BASE_WEEK] =A.[BASE_WEEK]and B.[RETAILERS]=A.[RETAILERS] ) AS SUM_BASE_SALES
  ,(select AVG(B.[DOLLAR]) from [dbo].[SQ11] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[UNITS]=A.[UNITS] AND B.[BASE_SALES_UNITS]=A.[BASE_SALES_UNITS] and B.[WEEK_TEXT]=A.[WEEK_TEXT] 
 AND B.[BASE_WEEK] =A.[BASE_WEEK]and B.[RETAILERS]=A.[RETAILERS] ) AS AVG_BASE_SALES
---INTO SQL12
 FROM [dbo].[SQL11] A


    SELECT *,ROUND((select MIN(B.[DOLLAR]) from [dbo].[SQL9] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[WEEK_TEXT] >=A.[PREV_13_WEEKS] and B.[WEEK_TEXT]<=A.[WEEK_TEXT]
 and B.[RETAILERS]=A.[RETAILERS]),2 ) AS MIN_L13_DOLLAR,
 ,ROUND((select MIN(B.[DOLLAR_YA]) from [dbo].[SQL9] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[WEEK_TEXT] >=A.[PREV_13_WEEKS] and B.[WEEK_TEXT]<=A.[WEEK_TEXT] 
 and B.[RETAILERS]=A.[RETAILERS]),2 ) AS MIN_L13_DOLLAR_YA
  ,ROUND((select SUM(B.[UNITS]) from [dbo].[SQL9] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[WEEK_TEXT] >=A.[BASE_START] and B.[WEEK_TEXT]<=A.[BASE_END] 
 and B.[RETAILERS]=A.[RETAILERS]),2 ) AS SUM_BASE_SALES_UNITS
  ,ROUND((select MAX(B.[DOLLAR]) from [dbo].[SQL9] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[WEEK_TEXT] >=A.[PREV_13_WEEKS] and B.[WEEK_TEXT]<=A.[WEEK_TEXT]
 and B.[RETAILERS]=A.[RETAILERS]),2 ) AS MAX_L13_DOLLAR
 ,ROUND((select MAX(B.[DOLLAR_YA]) from [dbo].[SQL9] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[WEEK_TEXT] >=A.[PREV_13_WEEKS] and B.[WEEK_TEXT]<=A.[WEEK_TEXT] 
 and B.[RETAILERS]=A.[RETAILERS]),2 ) AS MAX_L13_DOLLAR_YA
  ,ROUND((select MAX(B.[UNITS]) from [dbo].[SQL9] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[WEEK_TEXT] >=A.[BASE_START] and B.[WEEK_TEXT]<=A.[BASE_END] 
 and B.[RETAILERS]=A.[RETAILERS]),2 ) AS MAX_BASE_SALES_UNITS
 ,ROUND((select AVG(B.[DOLLAR]) from [dbo].[SQL9] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[WEEK_TEXT] >=A.[PREV_13_WEEKS] and B.[WEEK_TEXT]<=A.[WEEK_TEXT]
 and B.[RETAILERS]=A.[RETAILERS]),2 ) AS AVG_L13_DOLLAR
 ,ROUND((select AVG(B.[DOLLAR_YA]) from [dbo].[SQL9] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[WEEK_TEXT] >=A.[PREV_13_WEEKS] and B.[WEEK_TEXT]<=A.[WEEK_TEXT] 
 and B.[RETAILERS]=A.[RETAILERS]),2 ) AS AVG_L13_DOLLAR_YA
  ,ROUND((select AVG(B.[UNITS]) from [dbo].[SQL9] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[WEEK_TEXT] >=A.[BASE_START] and B.[WEEK_TEXT]<=A.[BASE_END] 
 and B.[RETAILERS]=A.[RETAILERS] ),2) AS AVG_BASE_SALES_UNITS
 INTO SQL10
  from [dbo].[SQL9] A


  
    SELECT *,ROUND((select MIN(B.[DOLLAR]) from [dbo].[SQL11] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B. [SECOND_QUARTER]>=A.[PREV_13_WEEKS] and B.[WEEK_TEXT]<=A.[SECOND_QUARTER]
 and B.[RETAILERS]=A.[RETAILERS]),2 ) AS MIN_NEW_L13_DOLLAR
 ,ROUND((select MIN(B.[DOLLAR_YA]) from [dbo].[SQL9] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[SECOND_QUARTER] >=A.[PREV_13_WEEKS] and B.[WEEK_TEXT]<=A.[SECOND_QUARTER]
 and B.[RETAILERS]=A.[RETAILERS]),2 ) AS MIN_NEW_L13_DOLLAR_YA
  ,ROUND((select SUM(B.[UNITS]) from [dbo].[SQL9] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[SECOND_QUARTER] >=A.[BASE_START] and B.[WEEK_TEXT]<=A.[BASE_END] 
 and B.[RETAILERS]=A.[RETAILERS]),2 ) AS SUM_NEW_BASE_SALES_UNITS
  ,ROUND((select MAX(B.[DOLLAR]) from [dbo].[SQL9] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[SECOND_QUARTER] >=A.[PREV_13_WEEKS] and B.[WEEK_TEXT]<=A.[SECOND_QUARTER]
 and B.[RETAILERS]=A.[RETAILERS]),2 ) AS MAX_NEW_L13_DOLLAR
 ,ROUND((select MAX(B.[DOLLAR_YA]) from [dbo].[SQL9] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[SECOND_QUARTER] >=A.[PREV_13_WEEKS] and B.[WEEK_TEXT]<=A.[SECOND_QUARTER]
 and B.[RETAILERS]=A.[RETAILERS]),2 ) AS MAX_NEW_L13_DOLLAR_YA
  ,ROUND((select MAX(B.[UNITS]) from [dbo].[SQL9] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[SECOND_QUARTER] >=A.[BASE_START] and B.[WEEK_TEXT]<=A.[BASE_END] 
 and B.[RETAILERS]=A.[RETAILERS]),2 ) AS MAX_NEW_BASE_SALES_UNITS
 ,ROUND((select AVG(B.[DOLLAR]) from [dbo].[SQL9] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B. [SECOND_QUARTER]>=A.[PREV_13_WEEKS] and B.[WEEK_TEXT]<=A.[SECOND_QUARTER]
 and B.[RETAILERS]=A.[RETAILERS]),2 ) AS AVG_NEW_L13_DOLLAR
 ,ROUND((select AVG(B.[DOLLAR_YA]) from [dbo].[SQL9] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[SECOND_QUARTER] >=A.[PREV_13_WEEKS] and B.[WEEK_TEXT]<=A.[SECOND_QUARTER]
 and B.[RETAILERS]=A.[RETAILERS]),2 ) AS AVG_NEW_L13_DOLLAR_YA
  ,ROUND((select AVG(B.[UNITS]) from [dbo].[SQL9] B
 where B.[ITEM_NUMBER]=A.[ITEM_NUMBER] and B.[SECOND_QUARTER] >=A.[BASE_START] and B.[WEEK_TEXT]<=A.[BASE_END] 
 and B.[RETAILERS]=A.[RETAILERS] ),2) AS AVG_NEW_BASE_SALES_UNITS
 into SQL12
 FROM SQL11 A

  SELECT * FROM file_2_N


  select A.[RETAILERS],A.[SUPER BRAND ],A.[DOLLAR],B.[AVG_UNIT_PRICE],B.[ITEM_NUMBER],B.[XDATE] from [dbo].[file_2_N] A 
  left join [dbo].[SQL12] B on A.[RETAILERS]=B.[RETAILERS]

  select a.*,b.* from [dbo].[file_2_N] a
  join [dbo].[SQL12] b on a.[RETAILERS]=b.[RETAILERS] and a.[CATEGORY]=b.[BC_SUPER_CATEGORY]

  select  a.[Unitsss],b.[BRAND_HIGH],a.[DOLLAR YA],b.[ONE_YEAR],b.[THIRD_QUARTER],b.[L13_DOLLAR] from [dbo].[file_2_N] a
   right join [dbo].[SQL12] b on a.[RETAILERS]=b.[RETAILERS] and a.[CATEGORY]=b.[BC_SUPER_CATEGORY]
 ---  group by [BRAND_HIGH]
  order by [BC_SUPER_CATEGORY]


   

   SELECT * FROM [dbo].[BOOK1]

   select 


   SELECT 
    [dbo].[BOOK1].*,
    CASE 
        WHEN [dbo].[SQL11].[DP_PARENT] IS NOT NULL THEN [dbo].[SQL11].[AVG_UNIT_PRICE]
        ELSE [dbo].[SQL11].[AVG_UNIT_PRICE] * 0.7
    END AS Result
FROM [dbo].[SQL11]
LEFT JOIN  [dbo].[BOOK1]  ON [dbo].[SQL11].[DP_PARENT] = [dbo].[BOOK1].[Parent]



